-- Airline DWH Project - Core OLTP Source Tables
-- Run this script first in Oracle.
-- These are the operational tables students extract using Oracle Connector in DataStage.

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  FLIGHT_COSTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  PAYMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  TICKETS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  RESERVATIONS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  FLIGHTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  ROUTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  AIRPORTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  AIRCRAFT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  PASSENGERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  FREQUENT_FLYER_TIERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  FARE_CLASSES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE  BOOKING_CHANNELS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE  AIRPORTS (
    AIRPORT_ID NUMBER  ,
    IATA_CODE VARCHAR2(3),
    AIRPORT_NAME VARCHAR2(120),
    CITY VARCHAR2(80),
    COUNTRY VARCHAR2(80),
    TIMEZONE VARCHAR2(80),
    TERMINAL_COUNT NUMBER
);

CREATE TABLE  AIRCRAFT (
    AIRCRAFT_ID NUMBER  ,
    TAIL_NUMBER VARCHAR2(20) ,
    MODEL VARCHAR2(80),
    MANUFACTURER VARCHAR2(80),
    CAPACITY_ECONOMY NUMBER,
    CAPACITY_BUSINESS NUMBER,
    CAPACITY_FIRST NUMBER,
    YEAR_MANUFACTURED NUMBER,
    STATUS VARCHAR2(30)
);

CREATE TABLE  ROUTES (
    ROUTE_ID NUMBER  ,
    ORIGIN_AIRPORT_ID NUMBER ,
    DESTINATION_AIRPORT_ID NUMBER,
    DISTANCE_KM NUMBER,
    FLIGHT_DURATION_MIN NUMBER,
    IS_INTERNATIONAL VARCHAR2(1),
    BASE_PRICE_USD NUMBER(10,2)
);

CREATE TABLE  FLIGHTS (
    FLIGHT_ID NUMBER  ,
    FLIGHT_NUMBER VARCHAR2(10),
    ROUTE_ID NUMBER ,
    AIRCRAFT_ID NUMBER ,
    SCHEDULED_DEPARTURE TIMESTAMP,
    SCHEDULED_ARRIVAL TIMESTAMP,
    ACTUAL_DEPARTURE TIMESTAMP,
    ACTUAL_ARRIVAL TIMESTAMP,
    STATUS VARCHAR2(30),
    ECONOMY_SEATS_AVAILABLE NUMBER,
    BUSINESS_SEATS_AVAILABLE NUMBER,
    FIRST_SEATS_AVAILABLE NUMBER
);

CREATE TABLE  FARE_CLASSES (
    FARE_CLASS_ID NUMBER  ,
    FARE_CODE VARCHAR2(5),
    FARE_DESCRIPTION VARCHAR2(80),
    CABIN VARCHAR2(30),
    REFUNDABLE VARCHAR2(1),
    MILES_MULTIPLIER NUMBER(5,2)
);

CREATE TABLE  BOOKING_CHANNELS (
    CHANNEL_ID NUMBER  ,
    CHANNEL_NAME VARCHAR2(50),
    CHANNEL_TYPE VARCHAR2(50),
    IS_ONLINE VARCHAR2(1)
);

CREATE TABLE  FREQUENT_FLYER_TIERS (
    TIER_ID NUMBER  ,
    TIER_NAME VARCHAR2(30),
    MIN_MILES NUMBER,
    LOUNGE_ACCESS VARCHAR2(1),
    PRIORITY_BOARDING VARCHAR2(1),
    UPGRADE_ELIGIBLE VARCHAR2(1),
    BONUS_MILES_PCT NUMBER(5,2)
);

CREATE TABLE  PASSENGERS (
    PASSENGER_ID NUMBER  ,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    GENDER VARCHAR2(1),
    DATE_OF_BIRTH DATE,
    NATIONALITY VARCHAR2(50),
    PASSPORT_NUMBER VARCHAR2(30),
    EMAIL VARCHAR2(120),
    PHONE VARCHAR2(40),
    FF_NUMBER VARCHAR2(20),
    TIER_ID NUMBER ,
    TOTAL_MILES NUMBER,
    JOIN_DATE DATE
);

CREATE TABLE  RESERVATIONS (
    RESERVATION_ID NUMBER  ,
    PASSENGER_ID NUMBER ,
    FLIGHT_ID NUMBER ,
    FARE_CLASS_ID NUMBER ,
    CHANNEL_ID NUMBER ,
    SEAT_NUMBER VARCHAR2(10),
    BOOKING_DATE DATE,
    PAYMENT_METHOD VARCHAR2(40),
    AMOUNT_PAID NUMBER(10,2),
    MILES_EARNED NUMBER,
    MILES_REDEEMED NUMBER,
    PROMO_ID NUMBER,
    IS_UPGRADE VARCHAR2(1),
    STATUS VARCHAR2(30)
);

CREATE TABLE  TICKETS (
    TICKET_ID NUMBER  ,
    TICKET_NUMBER VARCHAR2(30),
    RESERVATION_ID NUMBER ,
    PASSENGER_ID NUMBER,
    FLIGHT_ID NUMBER ,
    FARE_CLASS_ID NUMBER ,
    ISSUE_DATE DATE,
    SEAT_NUMBER VARCHAR2(10),
    BASE_FARE_USD NUMBER(10,2),
    TAX_AMOUNT_USD NUMBER(10,2),
    FEE_AMOUNT_USD NUMBER(10,2),
    DISCOUNT_AMOUNT_USD NUMBER(10,2),
    FINAL_TICKET_AMOUNT_USD NUMBER(10,2),
    TICKET_STATUS VARCHAR2(30),
    MILES_EARNED NUMBER,
    MILES_REDEEMED NUMBER
);

CREATE TABLE  PAYMENTS (
    PAYMENT_ID NUMBER  ,
    RESERVATION_ID NUMBER ,
    PAYMENT_DATE TIMESTAMP,
    PAYMENT_METHOD VARCHAR2(40),
    PAYMENT_AMOUNT_USD NUMBER(10,2),
    PAYMENT_STATUS VARCHAR2(30),
    CURRENCY_CODE VARCHAR2(3),
    TRANSACTION_REFERENCE VARCHAR2(50)
);

CREATE TABLE  FLIGHT_COSTS (
    FLIGHT_COST_ID NUMBER ,
    FLIGHT_ID NUMBER ,
    FUEL_COST_USD NUMBER(10,2),
    CREW_COST_USD NUMBER(10,2),
    AIRPORT_FEES_USD NUMBER(10,2),
    MAINTENANCE_COST_USD NUMBER(10,2),
    CATERING_COST_USD NUMBER(10,2),
    TOTAL_COST_USD NUMBER(10,2),
    COST_SOURCE VARCHAR2(40)
);

COMMIT;